### ISSUE TITLE
Can't connect to Deluge

### ISSUE THREAD

**Issue by titeishon** [JohnDoee/kodi-deluge-streaming#1]
Hi!
First of all, thanks for this awesome add-on!

I'm having issues connecting to my deluge server in my network. I've set up the thin client correctly, added my user and password in the auth file and so far I've managed to get the stream working with VLC on my Windows machine. For some reason it won't connect using the kodi add-on and the logs don't show anything useful. I've tried using the file serving port, the daemon port and even the web-ui port nonetheless it always shows an error when launching.

My Setup:
- Ubuntu 18.04 bionic
- Docker version 18.06.1-ce
- Linuxserver's deluge docker image ( https://hub.docker.com/r/linuxserver/deluge/ )
- Deluge 1.3.15
Kodi Players:
- Kodi v18 Leia Beta 1 on Windows 10
- Kodi v17.6 Krypton, Libreelec on a Raspberry Pi 3

Thanks!

**Comment by JohnDoee** [comment]
Can you connect to deluge daemon with deluge-gtk from your Kodi machine?

**Comment by titeishon** [comment]
Well I just tried right now and it just worked, can't exactly pinpoint what I was doing wrong because I just tried the same config... still, sorry for the false alarm.

Cheers
